#!/bin/bash

# Set up the python virtual environment and install dependencies
sudo apt update
sudo apt install pip -y
pip install -r requirements.txt

# Install ngrok
curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | \
sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && \
echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | \
sudo tee /etc/apt/sources.list.d/ngrok.list && \
sudo apt update && sudo apt install ngrok -y
ngrok config add-authtoken 2aYJromJ0rhB9oj54f11SHyFREE_2aNY3Zi6vgxbRTo6g8DTG

# Install other dependencies
sudo apt install gunicorn -y
sudo apt install pigpio -y

# Use piGPIO as the pin driver
echo 'export GPIOZERO_PIN_FACTORY=pigpio' >> ~/.bashrc

# Move the service files to the correct location
SERVICE_PATH=/etc/systemd/system
sudo cp gunicorn@.service $SERVICE_PATH
sudo cp ngrok.service $SERVICE_PATH

# Start the services
sudo systemctl start gunicorn@$(systemd-escape $PWD).service
sudo systemctl start ngrok.service
sudo systemctl start pigpiod

# Enable the services
sudo systemctl enable gunicorn@$(systemd-escape $PWD).service
sudo systemctl enable ngrok.service
sudo systemctl enable pigpiod
