#!/bin/bash

# Set up the python virtual environment and install dependencies
sudo apt update
sudo apt install pip
pip install -r requirements.txt

# Install ngrok
curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt install ngrok
ngrok config add-authtoken <token>

# Install gunicorn
sudo apt install gunicorn

# Move the service files to the correct location
SERVICE_PATH=/etc/systemd/system
sudo cp gunicorn@.service $SERVICE_PATH
sudo cp ngrok.service $SERVICE_PATH

# Enable the services
sudo systemctl enable gunicorn@$(systemd-escape --path $PWD).service
sudo systemctl enable ngrok.service

# Start the services
sudo systemctl start gunicorn@$(systemd-escape --path $PWD).service
sudo systemctl start ngrok.service